import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../../../domain/entities/event.dart';
import '../../../domain/entities/location_point.dart';
import '../../bloc/event/event_bloc.dart';
import '../../widgets/event/category_dropdowns.dart';
import '../../widgets/map/location_picker_widget.dart';

class CreateEventPage extends StatefulWidget {
  const CreateEventPage({super.key});

  @override
  State<CreateEventPage> createState() => _CreateEventPageState();
}

class _CreateEventPageState extends State<CreateEventPage> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();

  EventCategory? _selectedCategory;
  LocationPoint? _selectedLocation;

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  void _onCategoryChanged(EventCategory? category) {
    setState(() {
      _selectedCategory = category;
    });
  }

  void _onLocationSelected(LocationPoint location) {
    setState(() {
      _selectedLocation = location;
    });
  }

  EventSubCategory _getDefaultSubCategory(EventCategory category) {
    switch (category) {
      case EventCategory.music:
        return EventSubCategory.general;
      case EventCategory.sports:
        return EventSubCategory.general;
      case EventCategory.social:
        return EventSubCategory.meetup;
      case EventCategory.problem:
        return EventSubCategory.waterLeak;
      case EventCategory.other:
        return EventSubCategory.general;
    }
  }

  void _createEvent() {
    if (_formKey.currentState!.validate()) {
      if (_selectedLocation == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Veuillez sélectionner une position sur la carte'),
          ),
        );
        return;
      }

      final event = Event(
        id: '', // Will be generated by the backend/datasource
        creatorId: 'current-user', // In a real app, this would come from auth
        title: _titleController.text.trim(),
        description: _descriptionController.text.trim(),
        category: _selectedCategory!,
        subCategory: _getDefaultSubCategory(_selectedCategory!),
        location: _selectedLocation!,
        photoUrl: null,
        startTime: null,
        endTime: null,
        isActive: true, // Default to public
        createdAt: DateTime.now(),
      );

      context.read<EventBloc>().add(CreateEventRequested(event));
    }
  }

  @override
  Widget build(BuildContext context) {
    return BlocListener<EventBloc, EventState>(
      listener: (context, state) {
        if (state.status == EventStatus.success &&
            state.operation == EventOperation.create) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Événement créé avec succès!'),
              backgroundColor: Colors.green,
            ),
          );
          Navigator.of(context).pop();
        } else if (state.status == EventStatus.failure) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(state.message ?? 'Erreur lors de la création'),
              backgroundColor: Colors.red,
            ),
          );
        }
      },
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Créer un événement'),
          elevation: 0,
          centerTitle: true,
          actions: [
            BlocBuilder<EventBloc, EventState>(
              builder: (context, state) {
                final isLoading =
                    state.status == EventStatus.loading &&
                    state.operation == EventOperation.create;

                return Padding(
                  padding: const EdgeInsets.only(
                    left: 8.0,
                    top: 8.0,
                    right: 16.0,
                  ),
                  child: isLoading
                      ? const SizedBox(
                          width: 24,
                          height: 24,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: Colors.white,
                          ),
                        )
                      : TextButton(
                          onPressed: _createEvent,
                          style: TextButton.styleFrom(
                            backgroundColor: Theme.of(
                              context,
                            ).colorScheme.primary,
                            foregroundColor: Theme.of(
                              context,
                            ).colorScheme.onPrimary,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(8),
                            ),
                          ),
                          child: const Text(
                            'Publier',
                            style: TextStyle(
                              fontSize: 16,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),
                );
              },
            ),
          ],
        ),
        body: Form(
          key: _formKey,
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Title Field
                Card(
                  elevation: 0,
                  color: Theme.of(
                    context,
                  ).colorScheme.surfaceContainerHighest.withValues(alpha: 0.3),
                  child: Padding(
                    padding: const EdgeInsets.all(16),
                    child: TextFormField(
                      controller: _titleController,
                      decoration: const InputDecoration(
                        labelText: 'Nom de votre événement',
                        border: InputBorder.none,
                        hintText: 'ex: Concert de jazz au parc',
                        prefixIcon: Icon(Icons.event),
                      ),
                      style: const TextStyle(fontSize: 16),
                      validator: (value) {
                        if (value == null || value.trim().isEmpty) {
                          return 'Le titre est obligatoire';
                        }
                        return null;
                      },
                    ),
                  ),
                ),

                const SizedBox(height: 16),

                // Description Field
                Card(
                  elevation: 0,
                  color: Theme.of(
                    context,
                  ).colorScheme.surfaceContainerHighest.withValues(alpha: 0.3),
                  child: Padding(
                    padding: const EdgeInsets.all(16),
                    child: TextFormField(
                      controller: _descriptionController,
                      decoration: const InputDecoration(
                        labelText: 'Décrivez votre événement',
                        border: InputBorder.none,
                        hintText: 'Quelques mots sur votre événement...',
                        prefixIcon: Icon(Icons.description),
                        alignLabelWithHint: true,
                      ),
                      maxLines: 3,
                      style: const TextStyle(fontSize: 16),
                      validator: (value) {
                        if (value == null || value.trim().isEmpty) {
                          return 'La description est obligatoire';
                        }
                        return null;
                      },
                    ),
                  ),
                ),

                const SizedBox(height: 16),

                // Category Selection
                Card(
                  elevation: 0,
                  color: Theme.of(
                    context,
                  ).colorScheme.surfaceContainerHighest.withValues(alpha: 0.3),
                  child: Padding(
                    padding: const EdgeInsets.all(16),
                    child: CategoryDropdown(
                      selectedCategory: _selectedCategory,
                      onChanged: _onCategoryChanged,
                    ),
                  ),
                ),

                const SizedBox(height: 16),

                // Location Picker
                Card(
                  elevation: 0,
                  color: Theme.of(
                    context,
                  ).colorScheme.surfaceContainerHighest.withValues(alpha: 0.3),
                  child: Padding(
                    padding: const EdgeInsets.all(16),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            Icon(
                              Icons.location_on,
                              color: Theme.of(context).colorScheme.primary,
                            ),
                            const SizedBox(width: 8),
                            Text(
                              'Où se déroule l\'événement ?',
                              style: Theme.of(context).textTheme.titleMedium,
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),
                        LocationPickerWidget(
                          onLocationSelected: _onLocationSelected,
                          initialLocation: _selectedLocation,
                        ),
                      ],
                    ),
                  ),
                ),

                const SizedBox(height: 32), // Extra bottom space
              ],
            ),
          ),
        ),
      ),
    );
  }
}
