// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV1xW2uHcaMgUCsNrrCP0UgB_q5neFg6A',
    appId: '1:533741875324:android:b01e98d21196a429b0d9f9',
    messagingSenderId: '533741875324',
    projectId: 'mapster-4b696',
    storageBucket: 'mapster-4b696.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFY_z0ZUPsA6xZ7OYJ7_SIf6ZmUB3GZ2k',
    appId: '1:533741875324:ios:3d310f7dfcc91ffbb0d9f9',
    messagingSenderId: '533741875324',
    projectId: 'mapster-4b696',
    storageBucket: 'mapster-4b696.firebasestorage.app',
    iosClientId: '533741875324-0iacpsif6tq8tb89rcsg5hck1b2hn03q.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialnet',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb5mC9VC_dWc84DbQmA3jZrhszTsxAHyM',
    appId: '1:533741875324:web:3412c0441f47478bb0d9f9',
    messagingSenderId: '533741875324',
    projectId: 'mapster-4b696',
    authDomain: 'mapster-4b696.firebaseapp.com',
    storageBucket: 'mapster-4b696.firebasestorage.app',
    measurementId: 'G-2ZHPZGNRLB',
  );

}